//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessProject.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InterestingInfo
    {
        public short ID { get; set; }
        public string Interesting { get; set; }
        public string Information { get; set; }
        public string Who { get; set; }
    }
}
