//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessProject.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDetay
    {
        public int ID { get; set; }
        public Nullable<short> BlogID { get; set; }
        public string BlogImage1 { get; set; }
        public string BlogImage2 { get; set; }
        public string BlogComment1 { get; set; }
        public string BlogComment2 { get; set; }
        public string BlogSoz { get; set; }
    
        public virtual Tbl_Blog Tbl_Blog { get; set; }
    }
}
